title: Krishna Khadka
logo: /img.jpg
description: PhD Student at University of Texas at Arlington
theme: jekyll-theme-minimal

address: "Euless, Texas"
email: "Krishna.khadka@mavs.uta.edu"
linkedin: "https://www.linkedin.com/in/krishna-khadka-238b35162/"
twitter: "https://twitter.com/krishna200416"
googlescholar: "https://scholar.google.com/citations?user=fUIrcvkAAAAJ&hl=en"
