title: Krishna Khadka
logo: /img.jpg
description: PhD Candidate in Machine Learning & AI at UTA | Co-founder of Bhasha Tech
theme: jekyll-theme-minimal

address: "Dallas, Texas"
email: "krishna.khadka@mavs.uta.edu"
linkedin: "https://www.linkedin.com/in/krishna-khadka-238b35162/"
github: "https://github.com/krishnakhadka200416"
googlescholar: "https://scholar.google.com/citations?user=fUIrcvkAAAAJ&hl=en"
